car_info/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import CarViewSet
app_name = 'api'
router_v1 = DefaultRouter()

router_v1.register('cars',
                   CarViewSet,
                   basename='cars')

urlpatterns = [
    path('', include(router_v1.urls)),
]

car_info/cars/urls.py
from django.urls import path

from . import views

app_name = 'cars'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('car/<int:pk>/', views.CarDetailView.as_view(), name='detail'),
    path('car/<int:pk>/delete/', views.CarDeleteView.as_view(), name='delete'),
    path('car/<int:pk>/edit/', views.CarUpdateView.as_view(), name='edit'),
    path('car/', views.CarCreateView.as_view(), name='create'),
    path('car/<int:pk>/comment/',
         views.CommentCreateView.as_view(), name='comment'),
]

car_info/core/urls.py
from django.contrib import admin
from django.contrib.auth.forms import UserCreationForm
from django.urls import include, path, reverse_lazy
from django.views.generic.edit import CreateView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="cars_info",
        default_version='v1',
        description="Документация для cars_info",
        contact=openapi.Contact(email="ARTEM"),
        license=openapi.License(name="Hi"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

handler404 = 'cars.views.custom_404_view'
handler500 = 'cars.views.custom_500_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include("django.contrib.auth.urls")),
    path(
        'auth/signup/',
        CreateView.as_view(
            template_name='registration/signup.html',
            form_class=UserCreationForm,
            success_url=reverse_lazy('login'),
        ),
        name='signup',
    ),
    path('', include('cars.urls', namespace='cars')),
    path('api/', include('api.urls')),
    path('api/auth/', include('djoser.urls.jwt')),
    path('api/auth/', include('djoser.urls')),
    path('swagger<format>/',
         schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0),
         name='schema-swagger-ui'),
]

car_info/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'templates/css/styles.css' %}">
    <title> {% block title %}
    {% endblock title %} </title>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

car_info/templates/comment.html
{% extends "base.html" %}

{% block title %}
Добавление комметария
{% endblock title %}

{% block content %}
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Добавить</button>
</form> 
{% endblock content %}

car_info/templates/create.html
{% extends "base.html" %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование публикации
  {% elif "/delete/" in request.path %}
    Удаление публикации
  {% else %}
    Добавление публикации
  {% endif %}
{% endblock %}

{% block content %}
    {% with data=form.instance %}
    {% if "/edit/" in request.path %}
      <h1>Редактировать запись {{ data.pk }}</h1>
    {% elif "/delete/" in request.path %}
      <h1>Удалить запись {{ data.pk }}</h1>
    {% else %}
      <h1>Создать запись</h1>
    {% endif %}
      <form method="post">
        {% csrf_token %}
        {% if not "/delete/" in request.path %}
          {{ form }}
        {% else %}
          <p>{{ data.make }} {{ data.model }}</p>
          <p>{{ data.birthday }}</p>
        {% endif %}
        <button type="submit">Отправить</button>
      </form>
          
      {% endwith %}
{% endblock %}

car_info/templates/delete.html
{% extends "base.html" %}
{% block title %}
Успешно.
{% endblock title %}
{% block content %}
<h1>Запись удалена.</h1>
<a href="{% url 'cars:index' %}">Домой</a>
{% endblock content %}

car_info/templates/detail.html
{% extends "base.html" %}

{% block title %}
  {{ car.make }} {{ car.model }}
{% endblock %}

{% block content %}
    <a href="{% url 'cars:index' %}">Домой</a>
    <h1>{{ car.make }} {{car.model}}</h1>
    <p> Год: {{car.year}} </br>
    Описание: {{car.description}}</br>
    Обновлено: {{car.updated_at}}</br>
    Добавлено: {{car.created_at}}</br>
    Владелец: {{car.owner.username}}</br>
    </p>
    {% if user.id == car.owner.id%}
    <a href="{% url 'cars:edit' car.id %}">Отредактировать</a>
    <form action="{% url 'cars:delete' car.id %}" method="post" style="display:inline;">
      {% csrf_token %}
      <input type="hidden" name="delete" value="true">
      <button type="submit">Удалить</button>
    </form>
    {% endif %}
  </br>
    {% if user.is_authenticated%}
    <a href="{% url 'cars:comment' car.id %}">Добавить комментарий</a>
    {% endif %}
    {% for comment in comments %}
    <h3>{{ comment.author.username }}</h3>
    <p>{{ comment.content}}</p>
    <h5>{{ comment.created_at}}</h5>
    {% empty %}
    <p>Комментариев нет...</p>
    {% endfor %}


{% endblock %}

car_info/templates/edit.html
{% extends "base.html" %}

{% block title %}
Редактирование
{% endblock title %}
{% block content %}
<form method="post">
    {% csrf_token %}
      {{ form }}
    <button type="submit">Отправить</button>
  </form>
{% endblock content %}

car_info/templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Автомобили</h1>
<div id="auth">
{% if user.is_authenticated %}
  
    <p>С возвращением, {{ user.username }}!</p>
    <form method="post" action="{% url 'logout' %}">
      {% csrf_token %}
      <button type="submit">logout</button>
    <a href="{% url 'cars:create' %}">Новый автомобиль</a>
  </form>
  {% else %}
  <p>Вы не вошли:</p>
    <a href="{% url 'login' %}">Войти</a>
    <a href="{% url 'signup' %}">Регистрация</a>
  {% endif %}
</div>

<ul>
{% for car in cars %}
    <li><a href="{% url 'cars:detail' car.id %}">{{ car.make }} {{ car.model }}<a></li>
{% empty %}
    Машин нет.
{% endfor %}
</ul>
{% endblock content %}